# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-08 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('startup_name', models.CharField(max_length=50)),
                ('startup_description', models.CharField(max_length=800)),
                ('startup_website', models.CharField(max_length=50)),
                ('startup_fb', models.CharField(max_length=50)),
                ('startup_tw', models.CharField(max_length=50)),
                ('startup_youtube', models.CharField(max_length=50)),
                ('startup_logo', models.CharField(max_length=50)),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_title', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=50)),
            ],
        ),
    ]
